CARL provides the CA certificate within a PeerSetup to increase usability
eclipse-opendut/opendut pull request #121
Opened 2024-03-05 13:19 UTC by mtwardawski

added ca certificate to carls config files carl.toml and carl-development.toml, carl uses that ca certificate to generate peer setup. Decocec Ca Certificate was therefore added to setup string. Resolved a clippy finding in authenticated.rs.

2024-03-07 14:23 UTC, kKdH requested changes
Thank you for your contribution! ❤

2024-03-07 14:23 UTC, kKdH commented on opendut-carl/src/grpc/peer_manager.rs
> +    pub fn new(resources_manager: ResourcesManagerRef, vpn: Vpn, carl_url: Url, ca: String) -> Self {
use new-type instead of `String`

2024-03-07 14:23 UTC, kKdH commented on opendut-carl/src/grpc/peer_manager.rs
> +            "I'm a ca cert string".to_string()
use `include_str!()` and include `resources/development/tls/insecure-development-ca.pem`

2024-03-07 14:23 UTC, kKdH commented on opendut-carl/src/grpc/peer_manager.rs
> +            "I'm a ca cert string".to_string()
same as above

2024-03-07 14:23 UTC, kKdH commented on opendut-types/proto/opendut/types/util/net.proto
> +  string value = 1;
use `bytes` as datatype

2024-03-07 14:23 UTC, kKdH commented on opendut-types/src/util/net.rs
> +pub struct Certificate(pub String);
Maybe we can replace our new-type with a 'real' certificate type for example from rustls.

2024-03-11 15:36 UTC, reimarstier approved these changes
LGTM

2024-03-12 12:31 UTC, merged