CARL: issue-193 - Add Cleo release to Carls distribution and implemented new endpoint to download tarball with cleo and set-env script
eclipse-opendut/opendut pull request #205
Opened 2024-04-22 12:52 UTC by voelkera

closes #193

2024-04-23 13:39 UTC, reimarstier requested changes
At the moment the CI is failing with the following error:
```
# Log of opendut-carl
2024-04-22T15:23:59.260547Z  WARN spawn_server: opendut_carl: Could not write set-env-var.sh
thread 'main' panicked at opendut-carl/src/lib.rs:372:88:
Could not read metadata: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Please also note the other comments that were made. Further comments coming tomorrow.

2024-05-03 13:45 UTC, voelkera commented on doc/src/user-manual/cleo/install.md
> +The last thing to do, is to check if there is already a certificate, which is required to use CLEO.
Certificate is now part of the tarball that is being downloaded.

2024-05-03 14:25 UTC, voelkera commented on doc/src/user-manual/cleo/install.md
> +Once downloaded, extract the files with the command `tar -xvf opendut-cleo-{architecture}.tar.gz`. It will then be extracted into
updated

2024-05-03 14:25 UTC, voelkera commented on doc/src/user-manual/cleo/install.md
> +The archive can be requested at `https://{CARL-HOST}/api/cleo/{architecture}/download`.
architectures have been added

2024-05-07 10:42 UTC, voelkera commented on doc/src/user-manual/cleo/install.md
> +The tarball contains the `set-env-var.sh` shell script. It can be executed by the command `source set-env-var.sh`, which then sets the
script has been adjusted

2024-05-07 14:24 UTC, closed without merging